# Generated by Django 2.2.2 on 2019-07-01 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='slug',
            field=models.SlugField(max_length=100, null=True, unique=True, verbose_name=models.CharField(max_length=100)),
        ),
    ]
