# Generated by Django 2.2.2 on 2019-07-01 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190701_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='slug',
        ),
    ]
