# Generated by Django 2.2.2 on 2019-07-01 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_habit_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daily_Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_actions', models.PositiveIntegerField(default=0)),
                ('created_on', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='habit',
            old_name='daily_goal',
            new_name='habit_goal',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='date_started',
        ),
        migrations.AddField(
            model_name='habit',
            name='units',
            field=models.CharField(default='test', max_length=30),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Record',
        ),
        migrations.AddField(
            model_name='daily_record',
            name='habit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Habit'),
        ),
    ]
