# Generated by Django 2.2.2 on 2019-07-01 21:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190701_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_record',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
