# Generated by Django 2.2.2 on 2019-07-01 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190701_1739'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Daily_Record',
            new_name='DailyRecord',
        ),
    ]
