# Generated by Django 2.2.2 on 2019-07-02 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190701_1745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyrecord',
            old_name='created_on',
            new_name='record_date',
        ),
        migrations.AlterUniqueTogether(
            name='dailyrecord',
            unique_together={('habit', 'record_date')},
        ),
    ]
